(()=>{
 const NV={URL:'https://zcungofmmaagqcinafhb.supabase.co',KEY:'sb_publishable_7ydxbZOzF0v2X58P7Pk_jg_za4pBQ3s',API:'https://navaar-backend-production.up.railway.app'};
let WM=true;
const PLANP=(async()=>{try{
 if(!window.supabase)await loadJS('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2');
 const sb=window.supabase.createClient(NV.URL,NV.KEY),{data}=await sb.auth.getSession(),ss=data.session;if(!ss)return;
 const r=await fetch(NV.API+'/api/subscription/'+ss.user.id,{headers:{Authorization:'Bearer '+ss.access_token}});
 const d=await r.json();
 if(r.ok&&d.status==='active'&&(d.plan==='creator'||d.plan==='studio'))WM=false;
}catch(e){}})();
const PRE={
Poster:[1080,1350],Flyer:[1080,1350],BusinessCard:[1050,600],Invitation:[1080,1350],EventPoster:[1080,1350],ProductAdvertisement:[1080,1350],QuoteCard:[1080,1080],PoetryCard:[1080,1080],
InstagramPost:[1080,1080],InstagramStory:[1080,1920],InstagramReelCover:[1080,1920],InstagramCarousel:[1080,1080],WhatsAppStatus:[1080,1920],FacebookPost:[1200,630],FacebookStory:[1080,1920],FacebookCover:[1640,856],
YouTubeThumbnail:[1280,720],YouTubeChannelBanner:[2560,1440],YouTubeShortsCover:[1080,1920],TikTokCover:[1080,1920],LinkedInPost:[1200,627],LinkedInBanner:[1584,396],
UrduPoetry:[1080,1080],UrduQuote:[1080,1080],UrduStatus:[1080,1920],UrduPoster:[1080,1350],UrduThumbnail:[1280,720],UrduTextDesigner:[1080,1080],UrduTextAnimation:[1080,1920],UrduNameDesigner:[1080,1080]};
const FONTS=['Inter','Plus Jakarta Sans','Noto Nastaliq Urdu','Noto Sans Arabic','Georgia','Arial','Times New Roman','Impact','monospace'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=f=>new Promise((r,j)=>{let i=new Image;i.onload=()=>r(i);i.onerror=j;i.src=URL.createObjectURL(f)});
function mount(box,opt){
 const name=opt.preset||'InstagramPost',sz=PRE[name]||[1080,1080],key='nv-design-'+name;
 box.innerHTML=`<style>
 .dse{font:13px system-ui,sans-serif}.dse *{box-sizing:border-box}.dsbar{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:8px}.dsbar button,.dsbar select{min-height:38px}.dsg{display:grid;grid-template-columns:175px minmax(250px,1fr) 220px;gap:8px}.dsp{background:var(--p);border:1px solid var(--ln);border-radius:10px;padding:8px;overflow:auto}.dsp h3{font-size:12px;margin:5px 0}.dsp label{display:block;color:var(--mu);font-size:11px;margin:5px 0}.dsp input,.dsp select,.dsp textarea{width:100%;margin-top:3px}.dsgrid{display:grid;grid-template-columns:1fr 1fr;gap:4px}.dsstage{min-height:500px;display:flex;align-items:center;justify-content:center;background:radial-gradient(circle,#26353a,#0c1214);border:1px solid var(--ln);border-radius:10px;padding:10px}.dsstage canvas{max-width:100%;max-height:70vh;touch-action:none;box-shadow:0 12px 40px #0009}.dslayers button{width:100%;text-align:left;margin:2px 0}.dsstatus{color:var(--ac);min-height:18px;font-size:11px}.dsnote{color:var(--mu);font-size:11px;line-height:1.45}@media(max-width:900px){.dsg{grid-template-columns:1fr}.dsstage{min-height:55vh}.dsstage canvas{max-height:55vh}}
 </style><div class="dse"><div class="dsbar"><select class="preset" aria-label="Design preset">${Object.keys(PRE).map(x=>`<option value="${x}" ${x===name?'selected':''}>${x}</option>`).join('')}</select><button class="b" data-a="undo">↶ Undo</button><button class="b" data-a="redo">↷ Redo</button><button class="b" data-a="dup">Duplicate</button><button class="b" data-a="del">Delete</button><button class="b" data-a="front">Front</button><button class="b" data-a="back">Back</button><button class="b" data-a="save">Save</button><button class="b" data-a="load">Load</button><button class="b pri" data-a="png">Download PNG</button><button class="b" data-a="jpg">Download JPG</button></div>
 <div class="dsg"><aside class="dsp"><h3>Add objects</h3><button class="b" data-a="text">Add Text</button><button class="b" data-a="urdu">Add Urdu Text</button><button class="b" data-a="shape">Add Shape</button><label>Image<input class="image" type="file" accept="image/png,image/jpeg"></label><label>Logo / Watermark<input class="logo" type="file" accept="image/png,image/jpeg"></label><h3>Background</h3><div class="dsgrid"><input class="bg1" type="color" value="#102a2a"><input class="bg2" type="color" value="#1b1730"></div><label>Background image<input class="bgi" type="file" accept="image/png,image/jpeg"></label><h3>Alignment</h3><div class="dsgrid"><button class="b" data-a="left">Left</button><button class="b" data-a="center">Center</button><button class="b" data-a="right">Right</button><button class="b" data-a="top">Top</button><button class="b" data-a="middle">Middle</button><button class="b" data-a="bottom">Bottom</button></div><h3>Editable templates</h3><div class="dsgrid"><button class="b" data-t="clean">Clean</button><button class="b" data-t="quote">Quote</button><button class="b" data-t="sale">Sale</button><button class="b" data-t="poetry">Poetry</button></div><p class="dsnote">Canvas objects are real and editable. Urdu text uses RTL and browser font availability.</p></aside>
 <main class="dsstage"><canvas class="cv" width="${sz[0]}" height="${sz[1]}" aria-label="Editable design canvas"></canvas></main><aside class="dsp"><h3>Object properties</h3><div class="props"></div><h3>Layers</h3><div class="dslayers"></div><div class="dsstatus" role="status"></div></aside></div></div>`;
 const cv=box.querySelector('.cv'),c=cv.getContext('2d'),props=box.querySelector('.props'),layers=box.querySelector('.dslayers'),status=box.querySelector('.dsstatus');let bg='#102a2a',bg2='#1b1730',bgi=null,O=[],sel=-1,H=[],F=[],drag=null;
 const uid=()=>Math.random().toString(36).slice(2),snap=()=>JSON.stringify({bg,bg2,O:O.map(o=>{let q={...o};delete q.img;return q})}),push=()=>{H.push(snap());if(H.length>30)H.shift();F=[]},msg=t=>{status.textContent=t;setTimeout(()=>status.textContent='',2200)};
 function boxof(o){if(o.type==='text'){c.font=`${o.weight||600} ${o.size||50}px "${o.font||'Inter'}"`;return{w:Math.max(60,c.measureText(o.text||'').width),h:(o.size||50)*1.35}}return{w:o.w||200,h:o.h||120}}
 function wmark(){const s=Math.max(16,Math.round(cv.width*.035));c.save();c.globalAlpha=.8;c.shadowColor='rgba(0,0,0,.7)';c.shadowBlur=8;c.font='700 '+s+'px Arial,sans-serif';c.direction='ltr';c.textAlign='right';c.textBaseline='bottom';c.fillStyle='#fff';c.fillText('Made with Navaar Studio',cv.width-s*.8,cv.height-s*.8);c.restore()}
async function exportImg(q){await PLANP;const s=sel;sel=-1;draw();if(WM)wmark();const u=q==='png'?cv.toDataURL('image/png'):cv.toDataURL('image/jpeg',.92);sel=s;draw();const a=document.createElement('a');a.href=u;a.download='navaar-design.'+q;a.click();msg('Export complete.')}
 function draw(){c.clearRect(0,0,cv.width,cv.height);if(bgi)c.drawImage(bgi,0,0,cv.width,cv.height);else{let g=c.createLinearGradient(0,0,cv.width,cv.height);g.addColorStop(0,bg);g.addColorStop(1,bg2);c.fillStyle=g;c.fillRect(0,0,cv.width,cv.height)}O.forEach((o,i)=>{c.save();c.globalAlpha=o.opacity??1;c.translate(o.x,o.y);c.rotate((o.rot||0)*Math.PI/180);if(o.type==='text'){c.direction=o.rtl?'rtl':'ltr';c.textAlign='center';c.textBaseline='middle';c.font=`${o.italic?'italic ':''}${o.weight||600} ${o.size||50}px "${o.font||'Inter'}"`;c.fillStyle=o.color||'#fff';c.fillText(o.text||'',0,0)}else if(o.type==='shape'){c.fillStyle=o.color||'#79d9bd';if(o.shape==='circle'){c.beginPath();c.ellipse(0,0,o.w/2,o.h/2,0,0,Math.PI*2);c.fill()}else c.fillRect(-o.w/2,-o.h/2,o.w,o.h);if(o.stroke){c.strokeStyle=o.stroke;c.lineWidth=o.sw||2;c.stroke()}}else if(o.type==='image'&&o.img)c.drawImage(o.img,-o.w/2,-o.h/2,o.w,o.h);c.restore();if(i===sel){let r=boxof(o);c.save();c.translate(o.x,o.y);c.rotate((o.rot||0)*Math.PI/180);c.strokeStyle='#79d9bd';c.setLineDash([7,5]);c.strokeRect(-r.w/2-6,-r.h/2-6,r.w+12,r.h+12);c.restore()}})}
 function hit(px,py){for(let i=O.length-1;i>=0;i--){let o=O[i],r=boxof(o),a=-(o.rot||0)*Math.PI/180,dx=px-o.x,dy=py-o.y,rx=dx*Math.cos(a)-dy*Math.sin(a),ry=dx*Math.sin(a)+dy*Math.cos(a);if(Math.abs(rx)<=r.w/2+10&&Math.abs(ry)<=r.h/2+10)return i}return-1}
 function add(o){push();O.push(Object.assign({id:uid(),x:cv.width/2,y:cv.height/2,opacity:1,rot:0},o));sel=O.length-1;draw();render()}
 function render(){layers.innerHTML=O.map((o,i)=>`<button class="b" data-layer="${i}">${i===sel?'● ':''}${esc(o.name||o.type+' '+(i+1))}</button>`).join('')||'<span class="dsnote">No objects yet.</span>';if(sel<0||!O[sel]){props.innerHTML='<p class="dsnote">Select an object on the canvas.</p>';return}let o=O[sel],r=boxof(o);props.innerHTML=`<label>Text<textarea class="pt" dir="auto">${esc(o.text||'')}</textarea></label><label>Font<select class="pf">${FONTS.map(f=>`<option ${f===(o.font||'Inter')?'selected':''}>${f}</option>`).join('')}</select></label><div class="dsgrid"><label>Size<input class="ps" type="number" min="8" max="600" value="${o.size||50}"></label><label>Color<input class="pc" type="color" value="${o.color||'#ffffff'}"></label></div><div class="dsgrid"><label>X<input class="px" type="number" value="${Math.round(o.x)}"></label><label>Y<input class="py" type="number" value="${Math.round(o.y)}"></label></div><div class="dsgrid"><label>Width<input class="pw" type="number" value="${Math.round(r.w)}"></label><label>Height<input class="ph" type="number" value="${Math.round(r.h)}"></label></div><label>Rotation<input class="pr" type="range" min="-180" max="180" value="${o.rot||0}"></label><label>Opacity<input class="po" type="range" min="0" max="100" value="${Math.round((o.opacity??1)*100)}"></label><div class="dsgrid"><button class="b" data-p="bold">Bold</button><button class="b" data-p="italic">Italic</button></div><label>Direction<select class="pd"><option value="ltr">LTR</option><option value="rtl" ${o.rtl?'selected':''}>RTL</option></select></label>`;
 const bind=(s,fn)=>{let e=props.querySelector(s);if(e)e.oninput=e.onchange=()=>{push();fn(e.value);draw();render()}};bind('.pt',v=>{if(o.type==='text')o.text=v});bind('.pf',v=>o.font=v);bind('.ps',v=>o.size=Math.max(8,+v||50));bind('.pc',v=>o.color=v);bind('.px',v=>o.x=+v||0);bind('.py',v=>o.y=+v||0);bind('.pw',v=>{if(o.type!=='text')o.w=Math.max(10,+v||10)});bind('.ph',v=>{if(o.type!=='text')o.h=Math.max(10,+v||10)});bind('.pr',v=>o.rot=+v);bind('.po',v=>o.opacity=+v/100);bind('.pd',v=>o.rtl=v==='rtl');props.querySelectorAll('[data-p]').forEach(e=>e.onclick=()=>{push();if(e.dataset.p==='bold')o.weight=o.weight>=700?600:800;else o.italic=!o.italic;draw();render()})}
 function template(t){O=[];if(t==='sale'){add({type:'text',name:'SALE',text:'SALE',size:110,color:'#fff',weight:800,y:cv.height*.4});add({type:'text',name:'Offer',text:'50% OFF',size:70,color:'#d8b674',weight:800,y:cv.height*.58})}else if(t==='quote'){add({type:'text',name:'Quote',text:'آپ کی خوبصورت بات یہاں',font:'Noto Nastaliq Urdu',rtl:true,size:58,color:'#fff'});add({type:'text',name:'Author',text:'— Navaar Studio',size:28,color:'#79d9bd',y:cv.height*.7})}else if(t==='poetry')add({type:'text',name:'Poetry',text:'یہاں اپنی شاعری لکھیں',font:'Noto Nastaliq Urdu',rtl:true,size:62,color:'#fff'});else add({type:'text',name:'Title',text:name,size:60,color:'#fff',weight:800});draw();render()}
 box.addEventListener('click',e=>{let l=e.target.closest('[data-layer]');if(l){sel=+l.dataset.layer;draw();render();return}let t=e.target.closest('[data-t]');if(t){push();template(t.dataset.t);return}let a=e.target.closest('[data-a]');if(!a)return;let q=a.dataset.a;
 if(q==='text')add({type:'text',name:'Text',text:'Your text',size:54,color:'#fff',weight:700});if(q==='urdu')add({type:'text',name:'Urdu Text',text:'یہاں اپنا اردو متن لکھیں',font:'Noto Nastaliq Urdu',rtl:true,size:58,color:'#fff',weight:700});if(q==='shape')add({type:'shape',name:'Shape',shape:'rect',w:320,h:180,color:'#79d9bd'});
 if(q==='del'&&sel>=0){push();O.splice(sel,1);sel=-1;draw();render()}if(q==='dup'&&sel>=0){let o={...O[sel],id:uid(),x:O[sel].x+25,y:O[sel].y+25};delete o.img;push();O.splice(sel+1,0,o);sel++;draw();render()}if(q==='front'&&sel>=0){push();let o=O.splice(sel,1)[0];O.push(o);sel=O.length-1;draw();render()}if(q==='back'&&sel>=0){push();let o=O.splice(sel,1)[0];O.unshift(o);sel=0;draw();render()}
 if(q==='undo'&&H.length){F.push(snap());let z=JSON.parse(H.pop());bg=z.bg;bg2=z.bg2;O=z.O||[];sel=-1;draw();render()}if(q==='redo'&&F.length){H.push(snap());let z=JSON.parse(F.pop());bg=z.bg;bg2=z.bg2;O=z.O||[];sel=-1;draw();render()}
 if(['left','center','right','top','middle','bottom'].includes(q)&&sel>=0){push();let o=O[sel],r=boxof(o);if(q==='left')o.x=r.w/2+8;if(q==='center')o.x=cv.width/2;if(q==='right')o.x=cv.width-r.w/2-8;if(q==='top')o.y=r.h/2+8;if(q==='middle')o.y=cv.height/2;if(q==='bottom')o.y=cv.height-r.h/2-8;draw();render()}
 if(q==='save'){localStorage.setItem(key,JSON.stringify({bg,bg2,O:O.map(o=>{let z={...o};delete z.img;return z})}));msg('Design saved locally.')}if(q==='load'){let s=localStorage.getItem(key);if(!s)return msg('No saved design found.');let z=JSON.parse(s);bg=z.bg||bg;bg2=z.bg2||bg2;O=z.O||[];sel=-1;draw();render();msg('Saved design loaded.')}
 if(q==='png'||q==='jpg')exportImg(q);
 });
 box.querySelector('.preset').onchange=e=>{let s=PRE[e.target.value];cv.width=s[0];cv.height=s[1];O=[];sel=-1;draw();render()};box.querySelector('.bg1').oninput=e=>{bg=e.target.value;draw()};box.querySelector('.bg2').oninput=e=>{bg2=e.target.value;draw()};
 box.querySelector('.image').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let im=await read(f),k=Math.min(cv.width*.7/im.width,cv.height*.7/im.height,1);add({type:'image',name:f.name,img:im,w:im.width*k,h:im.height*k})}catch{msg('Only JPG and PNG images are supported.')}};
 box.querySelector('.logo').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let im=await read(f),k=Math.min(cv.width*.3/im.width,cv.height*.3/im.height,1);add({type:'image',name:'Logo / Watermark',img:im,w:im.width*k,h:im.height*k,opacity:.65})}catch{msg('Only JPG and PNG images are supported.')}};
 box.querySelector('.bgi').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{bgi=await read(f);draw()}catch{msg('Only JPG and PNG images are supported.')}};
 const pt=e=>{let r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*cv.width/r.width,y:(e.clientY-r.top)*cv.height/r.height}};cv.addEventListener('pointerdown',e=>{let p=pt(e);sel=hit(p.x,p.y);if(sel>=0){push();drag={x:p.x-O[sel].x,y:p.y-O[sel].y};cv.setPointerCapture(e.pointerId)}draw();render()});cv.addEventListener('pointermove',e=>{if(!drag||sel<0)return;let p=pt(e);O[sel].x=p.x-drag.x;O[sel].y=p.y-drag.y;draw()});cv.addEventListener('pointerup',()=>drag=null);
 let saved=localStorage.getItem(key);if(saved)try{let z=JSON.parse(saved);bg=z.bg||bg;bg2=z.bg2||bg2;O=z.O||[]}catch{}if(!O.length)O=[{id:uid(),type:'text',name:'Title',text:opt.urdu?'یہاں اپنا اردو متن لکھیں':name,font:opt.urdu?'Noto Nastaliq Urdu':'Plus Jakarta Sans',rtl:!!opt.urdu,size:58,color:'#fff',weight:700,x:cv.width/2,y:cv.height/2,opacity:1,rot:0}];draw();render();
}
window.NAVAAR_DESIGN={mount,PRE};
})();
