(()=>{
const{form,S,dl,rd,blob,XS,U,shell,flist,ld,pdfOut}=NVH,$=(s,r=document)=>r.querySelector(s),E='Something went wrong. Please try again.',NF='Please select a file first.',LAME='https://cdn.jsdelivr.net/npm/lamejs@1.2.1/lame.min.js';
/* ---------- audio helpers ---------- */
const AC=()=>new(window.AudioContext||window.webkitAudioContext)(),dec=async f=>{try{return await AC().decodeAudioData(await f.arrayBuffer())}catch(e){throw U('Your browser could not read this file. Try MP3, WAV or M4A.')}};
const FMT=['MP3 128 kbps','MP3 64 kbps (small)','MP3 192 kbps','WAV'];
function wav(ch,sr){const n=ch[0].length,c=ch.length,d=new DataView(new ArrayBuffer(44+n*c*2)),w=(o,s)=>[...s].forEach((x,i)=>d.setUint8(o+i,x.charCodeAt(0)));w(0,'RIFF');d.setUint32(4,36+n*c*2,true);w(8,'WAVEfmt ');d.setUint32(16,16,true);d.setUint16(20,1,true);d.setUint16(22,c,true);d.setUint32(24,sr,true);d.setUint32(28,sr*c*2,true);d.setUint16(32,c*2,true);d.setUint16(34,16,true);w(36,'data');d.setUint32(40,n*c*2,true);let o=44;for(let i=0;i<n;i++)for(let k=0;k<c;k++){const s=Math.max(-1,Math.min(1,ch[k][i]));d.setInt16(o,s<0?s*32768:s*32767,true);o+=2}return new Blob([d],{type:'audio/wav'})}
async function enc(ch,sr,f){if(f=='WAV')return[wav(ch,sr),'wav'];await loadJS(LAME);const e=new lamejs.Mp3Encoder(ch.length>1?2:1,sr,+f.match(/\d+/)[0]),ci=a=>{const o=new Int16Array(a.length);for(let i=0;i<a.length;i++){const s=Math.max(-1,Math.min(1,a[i]));o[i]=s<0?s*32768:s*32767}return o},L=ci(ch[0]),R=ch[1]?ci(ch[1]):0,p=[];for(let i=0;i<L.length;i+=1152){const d=R?e.encodeBuffer(L.subarray(i,i+1152),R.subarray(i,i+1152)):e.encodeBuffer(L.subarray(i,i+1152));d.length&&p.push(d)}p.push(e.flush());return[new Blob(p,{type:'audio/mpeg'}),'mp3']}
function proc(buf,o){const sr=buf.sampleRate,a=Math.floor(o.s*sr),z=Math.min(buf.length,Math.floor(o.e*sr));let ch=[...Array(buf.numberOfChannels).keys()].map(c=>buf.getChannelData(c).slice(a,z));if(o.sp!=1)ch=ch.map(d=>{const m=Math.floor(d.length/o.sp),r=new Float32Array(m);for(let i=0;i<m;i++){const p=i*o.sp,j=Math.floor(p),f=p-j;r[i]=d[j]*(1-f)+(d[j+1]??d[j])*f}return r});
 const len=ch[0].length;let g=o.vol;if(o.norm){let pk=0;ch.forEach(d=>{for(let i=0;i<d.length;i++)pk=Math.max(pk,Math.abs(d[i]))});if(pk)g*=.95/pk}const fi=Math.floor(o.fi*sr),fo=Math.floor(o.fo*sr);ch.forEach(d=>{for(let i=0;i<len;i++){let k=g;if(i<fi)k*=i/fi;if(i>len-fo)k*=(len-i)/fo;d[i]*=k}});if(o.rev)ch.forEach(d=>d.reverse());return ch}
const play=(ch,sr)=>{const c=AC(),b=c.createBuffer(ch.length,ch[0].length,sr);ch.forEach((d,i)=>b.copyToChannel(d,i));const s=c.createBufferSource();s.buffer=b;s.connect(c.destination);s.start();return()=>{try{s.stop();c.close()}catch(e){}}};
const A={
audioedit:b=>{let buf,stop=()=>{};b.innerHTML='<div class="fm"></div><canvas width="640" height="110" style="width:100%;background:#0006;border-radius:8px"></canvas><div class="row"><button class="b pv">▶ Preview</button><button class="b pri dl">Download</button></div>'+XS+'<p class="note">Speed changes pitch too. Volume above 100% can distort loud audio; use Normalize for safe loudness.</p>';
 const g=form($('.fm',b),[['file','Choose an audio file','audio/*'],['r','Start (‰ of track)',0,1000,0],['r','End (‰ of track)',0,1000,1000],['r','Fade in (seconds)',0,10,0],['r','Fade out (seconds)',0,10,0],['r','Volume %',0,400,100],['sel','Speed',['0.5x','0.75x','1x','1.25x','1.5x','2x']],['sel','Extras',['None','Normalize','Reverse','Normalize + Reverse']],['sel','Output format (smaller MP3 = compressed)',FMT]]),cv=$('canvas',b),x=cv.getContext('2d');clean=()=>stop();
 const opt=()=>{const v=g(),d=buf.duration;return{s:Math.min(v[1],v[2]-1)/1e3*d,e:Math.max(v[2],+v[1]+1)/1e3*d,fi:+v[3],fo:+v[4],vol:v[5]/100,sp:parseFloat(v[6]),norm:/Norm/.test(v[7]),rev:/Rev/.test(v[7])}},wf=()=>{if(!buf)return;const o=opt(),d=buf.getChannelData(0),W=cv.width,H=cv.height,k=Math.floor(d.length/W);x.clearRect(0,0,W,H);for(let i=0;i<W;i++){let m=0;for(let j=i*k;j<(i+1)*k;j+=Math.max(1,k>>5))m=Math.max(m,Math.abs(d[j]||0));const t=i/W*buf.duration,on=t>=o.s&&t<=o.e;x.fillStyle=on?'#6fd3b5':'#3a4a50';x.fillRect(i,H/2-m*H/2,1,Math.max(1,m*H))}S(b,`Selection: ${o.s.toFixed(1)}s to ${o.e.toFixed(1)}s of ${buf.duration.toFixed(1)}s`)};
 b.onchange=b.oninput=async e=>{if(e.target.type=='file'){const f=e.target.files[0];if(!f)return;S(b,'Reading audio…');try{buf=await dec(f)}catch(er){return S(b,er.message)}}wf()};
 $('.pv',b).onclick=()=>{stop();if(!buf)return S(b,NF);stop=play(proc(buf,opt()),buf.sampleRate)};
 $('.dl',b).onclick=async()=>{if(!buf)return S(b,NF);S(b,'Processing audio…');try{const[bl,ex]=await enc(proc(buf,opt()),buf.sampleRate,g()[8]);dl(bl,'navaar-audio.'+ex);S(b,'Downloaded ('+Math.round(bl.size/1024)+' KB)')}catch(er){S(b,er.user?er.message:E)}}},
audiojoin:b=>{b.innerHTML='<div></div><div></div>';const F=flist(b.children[0],'audio/*','Add audio files (order = play order)');shell(b.children[1],[['sel','Output format',FMT]],'Join audio',async(v,bx)=>{if(F.length<2)throw U('Please add at least two audio files.');const bs=[];for(const f of F){S(bx,'Reading '+f.name+'…');bs.push(await dec(f))}const sr=bs[0].sampleRate,C=Math.max(...bs.map(z=>z.numberOfChannels)),n=bs.reduce((a,z)=>a+z.length,0),ch=Array.from({length:C},()=>new Float32Array(n));let o=0;bs.forEach(z=>{for(let c=0;c<C;c++)ch[c].set(z.getChannelData(Math.min(c,z.numberOfChannels-1)),o);o+=z.length});const[bl,ex]=await enc(ch,sr,v[0]);dl(bl,'navaar-joined.'+ex);S(bx,'Done. '+F.length+' files joined.')})},
audioconv:b=>shell(b,[['file','Choose an audio or video file','audio/*,video/*'],['sel','Convert to',FMT]],'Convert',async(v,bx)=>{const f=v[0][0];if(!f)throw U(NF);const z=await dec(f),ch=[...Array(z.numberOfChannels).keys()].map(c=>z.getChannelData(c)),[bl,ex]=await enc(ch,z.sampleRate,v[1]);dl(bl,'navaar-audio.'+ex);S(bx,'Done. Downloaded '+Math.round(bl.size/1024)+' KB.')}),
recorder:b=>{b.innerHTML='<div class="big rt">00:00</div><div class="row"><button class="b pri rs">● Record</button><button class="b st" disabled>■ Stop</button></div>'+XS+'<audio controls style="width:100%;display:none"></audio><div class="row dd" style="display:none"><button class="b d1">Download</button><button class="b d2">Download MP3</button></div>';let ms,mr,ch=[],iv,bl;const stopT=()=>{clearInterval(iv);ms&&ms.getTracks().forEach(t=>t.stop())};clean=()=>{stopT();try{mr.state=='recording'&&mr.stop()}catch(e){}};
 $('.rs',b).onclick=async()=>{try{ms=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}})}catch(e){return S(b,'Microphone permission is required.')}if(!window.MediaRecorder)return S(b,'This browser cannot record audio.');mr=new MediaRecorder(ms);ch=[];mr.ondataavailable=e=>ch.push(e.data);mr.onstop=()=>{stopT();bl=new Blob(ch,{type:mr.mimeType});const a=$('audio',b);a.src=URL.createObjectURL(bl);a.style.display='block';$('.dd',b).style.display='flex';$('.rs',b).disabled=false;$('.st',b).disabled=true;S(b,'Recording ready.')};mr.start();const t0=Date.now();iv=setInterval(()=>{const s=Math.floor((Date.now()-t0)/1e3);$('.rt',b).textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')},250);$('.rs',b).disabled=true;$('.st',b).disabled=false;S(b,'Recording…')};
 $('.st',b).onclick=()=>mr&&mr.stop();$('.d1',b).onclick=()=>dl(bl,'navaar-recording.'+(bl.type.includes('ogg')?'ogg':bl.type.includes('mp4')?'m4a':'webm'));
 $('.d2',b).onclick=async()=>{S(b,'Converting…');try{const z=await dec(bl),[o]=await enc([z.getChannelData(0)],z.sampleRate,FMT[0]);dl(o,'navaar-recording.mp3');S(b,'Downloaded')}catch(e){S(b,E)}}},
tts:(b,ur)=>{if(!window.speechSynthesis){b.innerHTML='<p class="mu">Your browser does not support text to speech.</p>';return}const LG=[['Urdu','ur'],['Hindi','hi'],['English (US)','en-US'],['English (UK)','en-GB']];b.innerHTML='<div class="fm"></div><label>Voice<select class="vc"></select></label><div class="row"><button class="b pri sp">▶ Speak</button><button class="b sx">■ Stop</button></div>'+XS+'<p class="note">Voices depend on your device and browser (names show male/female where the device says so). Browsers cannot save this speech as a file. To put a voice in a video, use the Audio Recorder or the Video Editor.</p>';
 const g=form($('.fm',b),[['t','Text','','',''],['sel','Language',LG.map(l=>l[0])],['r','Speed %',30,200,100],['r','Pitch %',0,200,100],['r','Volume %',0,100,100]]),vs=()=>{const p=LG.find(l=>l[0]==g()[1])[1].toLowerCase(),a=speechSynthesis.getVoices().filter(v=>v.lang.toLowerCase().startsWith(p.slice(0,2))&&(p.length<3||v.lang.toLowerCase()==p||1));$('.vc',b).innerHTML=a.length?a.map(v=>`<option value="${esc(v.name)}">${esc(v.name)} (${esc(v.lang)})</option>`).join(''):'<option value="">No voice found for this language on your device</option>'};
 if(ur)$('select[data-i="1"]',b).value='Urdu';vs();speechSynthesis.onvoiceschanged=vs;clean=()=>speechSynthesis.cancel();b.onchange=e=>{if(e.target.dataset.i=='1')vs()};b.oninput=()=>S(b,g()[0].length+' characters');
 $('.sp',b).onclick=()=>{const v=g();if(!v[0].trim())return S(b,'Please type some text first.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(v[0]),n=$('.vc',b).value,f=speechSynthesis.getVoices().find(z=>z.name==n);if(f){u.voice=f;u.lang=f.lang}else u.lang=LG.find(l=>l[0]==v[1])[1];u.rate=v[2]/100;u.pitch=v[3]/100;u.volume=v[4]/100;speechSynthesis.speak(u)};$('.sx',b).onclick=()=>speechSynthesis.cancel()}};/* ---------- design & Urdu studio ---------- */
const isPaid=()=>false;
const FONTS=['Noto Nastaliq Urdu','Noto Naskh Arabic','Amiri','Aref Ruqaa','Playfair Display','Poppins','Impact','Georgia'],SZ={'Instagram Post 1080×1080':[1080,1080],'Instagram Portrait 1080×1350':[1080,1350],'Story / WhatsApp Status / TikTok 1080×1920':[1080,1920],'Poster 1080×1527':[1080,1527],'Flyer 1240×1748':[1240,1748],'Invitation 1080×1440':[1080,1440],'Business Card 1050×600':[1050,600],'YouTube Thumbnail 1280×720':[1280,720],'YouTube Banner 2560×1440':[2560,1440],'Facebook Post 1200×630':[1200,630],'Facebook Cover 820×312':[820,312],'LinkedIn Banner 1584×396':[1584,396]};
const fonts=async()=>{if(!$('#gf')){const l=document.createElement('link');l.id='gf';l.rel='stylesheet';l.href='https://fonts.googleapis.com/css2?family=Noto+Nastaliq+Urdu&family=Noto+Naskh+Arabic&family=Amiri&family=Aref+Ruqaa&family=Playfair+Display&family=Poppins:wght@400;700&display=swap';document.head.appendChild(l)}try{await Promise.all(FONTS.slice(0,6).map(f=>document.fonts.load('24px "'+f+'"','لفظ Aa')))}catch(e){}};
const PR={text:[['tx','Text','t'],['ff','Font','sel'],['fs','Size','r',10,500],['c','Color','c'],['sh','Shadow / glow','r',0,60]],shape:[['k','Shape','sel'],['c','Color','c'],['w','Width','r',20,2600],['h','Height','r',20,2600],['r','Corner radius','r',0,500]],img:[['w','Width','r',20,2600]]};
async function studio(b,pre){await fonts();const st={w:1080,h:1350,c1:'#132a2b',c2:'#0b1a1c',dim:30,an:'None'},L=[];let sel=-1,bg,bf,drag,ff;
 b.innerHTML='<div class="f0"></div><div class="row"><button class="b" data-a="text">+ Text</button><button class="b" data-a="rect">+ Shape</button></div><label>Add image or logo<input type="file" accept="image/*" class="ai"></label><canvas style="max-width:100%;border-radius:8px;touch-action:none;background:#000"></canvas><p class="note">Drag items on the picture to move them.</p><div class="row ly"></div><div class="pp"></div><div class="row"><button class="b pri dp">Download PNG</button><button class="b dj">Download JPG</button><button class="b pa">▶ Preview animation</button><button class="b dv">Download video (.webm)</button></div>'+XS+'<p class="note">Video has no sound. Add music in the Video Editor.</p>';
 const cv=$('canvas',b),x=cv.getContext('2d'),g0=form($('.f0',b),[['sel','Canvas size',Object.keys(SZ)],['c','Background color 1',st.c1],['c','Background color 2',st.c2],['file','Background image (optional)','image/*'],['r','Image dim %',0,80,30],['sel','Text animation (video & preview)',['None','Fade','Slide up','Zoom','Typewriter','Letter reveal','Glow']],['file','Add your own font (.ttf .otf .woff2)','.ttf,.otf,.woff,.woff2']]);
 const draw=(p=1,ex)=>{cv.width=st.w;cv.height=st.h;const g=x.createLinearGradient(0,0,st.w*.4,st.h);g.addColorStop(0,st.c1);g.addColorStop(1,st.c2);x.fillStyle=g;x.fillRect(0,0,st.w,st.h);if(bg){const k=Math.max(st.w/bg.width,st.h/bg.height);x.drawImage(bg,(st.w-bg.width*k)/2,(st.h-bg.height*k)/2,bg.width*k,bg.height*k);x.fillStyle=`rgba(0,0,0,${st.dim/100})`;x.fillRect(0,0,st.w,st.h)}
  L.forEach((o,i)=>{x.save();let a=o.op/100,dx=0,dy=0,sc=1,tx=o.tx||'';const q=Math.min(1,p/.35),an=st.an;if(o.t=='text'){if(an=='Fade')a*=q;if(an=='Slide up'){a*=q;dy=(1-q)*90}if(an=='Zoom'){a*=q;sc=.6+.4*q}if(an=='Typewriter')tx=[...tx].slice(0,Math.ceil([...tx].length*Math.min(1,p/.7))).join('');if(an=='Letter reveal')tx=tx.split(' ').slice(0,Math.ceil(tx.split(' ').length*Math.min(1,p/.7))).join(' ')}
   x.globalAlpha=a;x.translate(o.x+dx,o.y+dy);x.rotate(o.rot*Math.PI/180);x.scale(sc,sc);
   if(o.t=='text'){x.font=`700 ${o.fs}px "${o.ff}",sans-serif`;x.fillStyle=o.c;x.textAlign='center';x.textBaseline='middle';x.direction=/[\u0600-\u06FF]/.test(o.tx)?'rtl':'ltr';if(an=='Glow'){x.shadowColor=o.c;x.shadowBlur=20+20*Math.abs(Math.sin(p*12))}else if(+o.sh){x.shadowColor=o.c+'cc';x.shadowBlur=+o.sh}const lh=o.fs*1.6,full=o.tx.split('\n');o.w=Math.max(20,...full.map(l=>x.measureText(l).width));o.h=full.length*lh;const ls=tx.split('\n');ls.forEach((l,k)=>x.fillText(l,0,(k-(full.length-1)/2)*lh))}
   else if(o.t=='shape'){x.fillStyle=o.c;x.beginPath();o.k=='circle'?x.ellipse(0,0,o.w/2,o.h/2,0,0,7):x.roundRect(-o.w/2,-o.h/2,o.w,o.h,+o.r);x.fill()}else x.drawImage(o.im,-o.w/2,-o.h/2,o.w,o.h);
   if(i==sel&&!ex){x.globalAlpha=1;x.shadowBlur=0;x.strokeStyle='#6fd3b5';x.lineWidth=Math.max(2,st.w/300);x.setLineDash([12,8]);x.strokeRect(-o.w/2-6,-o.h/2-6,o.w+12,o.h+12)}x.restore()});if(ex&&!isPaid()){x.save();x.globalAlpha=.75;x.fillStyle='#fff';x.shadowColor='rgba(0,0,0,.65)';x.shadowBlur=6;x.font='600 '+Math.round(st.w/38)+'px Arial,sans-serif';x.textAlign='right';x.textBaseline='alphabetic';x.direction='ltr';x.fillText('Made with Navaar Studio',st.w-st.w/40,st.h-st.h/40);x.restore()}};
 const list=()=>{$('.ly',b).innerHTML=L.map((o,i)=>`<button class="b" data-s="${i}" style="${i==sel?'border-color:var(--ac)':''}">${i+1}. ${o.t=='text'?esc(o.tx.slice(0,10)):o.t=='shape'?o.k:'image'}</button>`).join('')},R=()=>{draw();list()};
 const props=()=>{const o=L[sel],pp=$('.pp',b);if(!o){pp.innerHTML='<p class="mu">Tap an item to edit it, or add text, a shape or an image.</p>';return}pp.innerHTML=[...PR[o.t],['rot','Rotate °','r',-180,180],['op','Opacity %','r',5,100]].map(([k,l,ty,a,z])=>`<label>${l}`+(ty=='t'?`<textarea data-k="${k}" dir="auto">${esc(o[k])}</textarea>`:ty=='sel'?`<select data-k="${k}">${(k=='ff'?FONTS:['rect','circle']).map(f=>`<option ${f==o[k]?'selected':''}>${f}</option>`).join('')}</select>`:ty=='c'?`<input data-k="${k}" type="color" value="${o[k]}">`:`<input data-k="${k}" type="range" min="${a}" max="${z}" value="${o[k]}">`)+'</label>').join('')+'<div class="row"><button class="b" data-a="dup">Duplicate</button><button class="b" data-a="up">Forward</button><button class="b" data-a="dn">Back</button><button class="b" data-a="del">Delete</button></div>'};
 const add=o=>{L.push({x:st.w/2,y:st.h/2,rot:0,op:100,w:200,h:100,...o});sel=L.length-1;props();R()},sync=async()=>{const v=g0(),[w,h]=SZ[v[0]];L.forEach(o=>{o.x*=w/st.w;o.y*=h/st.h});Object.assign(st,{w,h,c1:v[1],c2:v[2],dim:+v[4],an:v[5]});if(v[3][0]!==bf){bf=v[3][0];bg=null;if(bf)try{bg=await rd(bf)}catch(e){S(b,'Your browser may not support this image format.')}}if(v[6][0]&&v[6][0]!==ff){ff=v[6][0];const nm=ff.name.replace(/\.\w+$/,'');try{const f=new FontFace(nm,'url('+URL.createObjectURL(ff)+')');await f.load();document.fonts.add(f);FONTS.push(nm);props();S(b,'Font added: '+nm)}catch(e){S(b,'Could not load this font file.')}}R()};
 b.querySelector('.f0').oninput=b.querySelector('.f0').onchange=sync;
 $('.ai',b).onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const im=await rd(f),k=Math.min(1,st.w*.6/im.width);add({t:'img',im,w:im.width*k,h:im.height*k})}catch(er){S(b,'Your browser may not support this image format.')}e.target.value=''};
 b.onclick=e=>{const a=e.target.closest('[data-a]'),s=e.target.closest('[data-s]');if(s){sel=+s.dataset.s;props();R();return}if(!a)return;const o=L[sel],k=a.dataset.a;if(k=='text')add({t:'text',tx:pre?'لفظوں کو منظر دو':'Your text',ff:pre?FONTS[0]:'Poppins',fs:Math.round(st.w/12),c:'#ffffff',sh:0});if(k=='rect')add({t:'shape',k:'rect',w:st.w*.5,h:st.h*.15,r:24,c:'#dcb56e'});if(!o)return;if(k=='del'){L.splice(sel,1);sel=-1}if(k=='dup'){L.push({...o,x:o.x+30,y:o.y+30});sel=L.length-1}if(k=='up'&&sel<L.length-1){[L[sel],L[sel+1]]=[L[sel+1],L[sel]];sel++}if(k=='dn'&&sel>0){[L[sel],L[sel-1]]=[L[sel-1],L[sel]];sel--}props();R()};
 const pp=$('.pp',b);pp.oninput=pp.onchange=e=>{const k=e.target.dataset.k,o=L[sel];if(!k||!o)return;o[k]=e.target.type=='range'?+e.target.value:e.target.value;R();if(k=='tx')list()};
 const pt=e=>{const r=cv.getBoundingClientRect();return[(e.clientX-r.left)*cv.width/r.width,(e.clientY-r.top)*cv.height/r.height]};
 cv.onpointerdown=e=>{const[px,py]=pt(e);for(let i=L.length-1;i>=0;i--){const o=L[i],a=-o.rot*Math.PI/180,dx=px-o.x,dy=py-o.y;if(Math.abs(dx*Math.cos(a)-dy*Math.sin(a))<=o.w/2+6&&Math.abs(dx*Math.sin(a)+dy*Math.cos(a))<=o.h/2+6){sel=i;drag=[o.x-px,o.y-py];cv.setPointerCapture(e.pointerId);props();R();return}}sel=-1;props();R()};
 cv.onpointermove=e=>{if(!drag||sel<0)return;const[px,py]=pt(e);L[sel].x=px+drag[0];L[sel].y=py+drag[1];draw()};cv.onpointerup=()=>drag=null;
 const out=async t=>{if(!L.length)return S(b,'Add some text or an image first.');draw(1,1);let bl;if(t=='image/jpeg'){const c=document.createElement('canvas');c.width=cv.width;c.height=cv.height;c.getContext('2d').drawImage(cv,0,0);bl=await blob(c,t,.92)}else bl=await blob(cv,t);dl(bl,'navaar-design.'+(t=='image/png'?'png':'jpg'));R();S(b,'Downloaded')};
 $('.dp',b).onclick=()=>out('image/png');$('.dj',b).onclick=()=>out('image/jpeg');
 const run=rec=>{if(rec&&!window.MediaRecorder)return S(b,'Video export needs Chrome, Edge or Firefox.');if(st.an=='None'&&rec)S(b,'Tip: choose a text animation above for a moving video.');let mr,ch=[];if(rec){mr=new MediaRecorder(cv.captureStream(30),{mimeType:'video/webm'});mr.ondataavailable=e=>ch.push(e.data);mr.onstop=()=>{dl(new Blob(ch,{type:'video/webm'}),'navaar-video.webm');R();S(b,'Video downloaded')};mr.start();S(b,'Recording video…')}const t0=performance.now(),D=5e3,f=()=>{const p=Math.min(1,(performance.now()-t0)/D);draw(p,1);if(p<1)requestAnimationFrame(f);else if(rec)setTimeout(()=>mr.stop(),200);else R()};f()};
 $('.pa',b).onclick=()=>run(0);$('.dv',b).onclick=()=>L.length?run(1):S(b,'Add some text or an image first.');
 if(pre){$('select[data-i="0"]',b).value=pre.z;await sync();$('.f0 input[data-i="1"]',b).value=st.c1=pre.c1;$('.f0 input[data-i="2"]',b).value=st.c2=pre.c2;add({t:'text',tx:pre.t,ff:FONTS[0],fs:Math.round(st.w/13),c:'#ffffff',sh:12,y:st.h/2});if(pre.a)add({t:'text',tx:pre.a,ff:'Poppins',fs:Math.round(st.w/30),c:'#dcb56e',sh:0,y:st.h/2+st.h*.14});sel=0}props();R()}
const pre=(z,c1,c2,t,a)=>b=>studio(b,{z,c1,c2,t,a});
Object.assign(window.NVX,A,{urdutts:b=>A.tts(b,1),design:b=>studio(b),
urdupoetry:pre('Instagram Portrait 1080×1350','#12303a','#0b1a1c','ہزاروں خواہشیں ایسی کہ ہر خواہش پہ دم نکلے\nبہت نکلے مرے ارمان لیکن پھر بھی کم نکلے','— شاعر کا نام'),
urduquote:pre('Instagram Post 1080×1080','#2a1a33','#120a18','جو ملا اُسی میں خوش رہنا سیکھو','— اقتباس'),
urdustatus:pre('Story / WhatsApp Status / TikTok 1080×1920','#33201a','#160c08','دل کو سکون دو','@navaar'),
urduposter:pre('Poster 1080×1527','#0b3d3a','#06201f','اردو مشاعرہ\nآج شام ۸ بجے','ہال نمبر ۱'),
urduthumb:pre('YouTube Thumbnail 1280×720','#4a1f6b','#1d0a2b','اردو شاعری کا سفر','')})
Object.assign(window.NVX, {
  pdfmeta: function(b){ return shell(b, [['file','Choose a PDF','application/pdf'],['s','Title',''],['s','Author',''],['s','Subject',''],['s','Keywords','']], 'Apply metadata', async function(v,bx){ const f=v[0][0]; if(!f) throw U(NF); const d=await ld(f); d.setTitle(v[1]); d.setAuthor(v[2]); d.setSubject(v[3]); d.setKeywords((v[4]||'').split(',').map(x=>x.trim()).filter(Boolean)); await pdfOut(d,bx,'Metadata applied and PDF downloaded.'); }); },
  pdfcompress: function(b){ return shell(b, [['file','Choose a PDF','application/pdf'],['sel','Mode',['Re-save / optimize structure','Remove metadata + re-save']]], 'Optimize PDF', async function(v,bx){ const f=v[0][0]; if(!f) throw U(NF); const d=await ld(f); if(v[1].includes('Remove')){d.setTitle('');d.setAuthor('');d.setSubject('');d.setKeywords([]);} await pdfOut(d,bx,'PDF re-saved successfully. Browser compression is structural; embedded image recompression is not performed.'); }); }
});
})();
