(()=>{const $=(s,r=document)=>r.querySelector(s),E='Something went wrong. Please try again.',NF='Please select a file first.',U=m=>{const e=new Error(m);e.user=1;return e},S=(b,m)=>{const e=$('.xs',b);if(e)e.textContent=m},
PL='https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js',PJ='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js',QRL='https://cdn.jsdelivr.net/npm/qrcode-generator@1.4.4/qrcode.js',JS='https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.js',JB='https://cdn.jsdelivr.net/npm/jsbarcode@3.11.6/dist/JsBarcode.all.min.js',
dl=(b,n)=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),4e3)},
rd=f=>new Promise((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=URL.createObjectURL(f)}),kb=n=>n>1048576?(n/1048576).toFixed(2)+' MB':Math.round(n/1024)+' KB',
blob=(c,t,q)=>new Promise(r=>c.toBlob(r,t,q)),XS='<div class="xs" style="color:var(--ac);min-height:22px" role="status"></div>';
function form(box,spec){box.innerHTML=spec.map(([k,l,a,b,c],i)=>{const n=`data-i="${i}"`;return`<label>${l}`+(k=='file'?`<input ${n} type="file" accept="${a}"${b?' multiple':''}>`:k=='sel'?`<select ${n}>${a.map(o=>`<option>${o}</option>`).join('')}</select>`:k=='r'?`<input ${n} type="range" min="${a}" max="${b}" value="${c}">`:k=='t'?`<textarea ${n} dir="auto">${a??''}</textarea>`:`<input ${n} type="${{s:'text',n:'number',c:'color'}[k]}" value="${a??''}">`)+'</label>'}).join('');return()=>[...box.querySelectorAll('[data-i]')].map(e=>e.type=='file'?e.files:e.value)}
/* ---- image tools ---- */
function imgTool(box,name,spec,draw){box.innerHTML='<div class="fm"></div><label>Format<select class="fmt"><option>PNG</option><option>JPG</option><option>WebP</option></select></label><label>Quality (JPG / WebP)<input class="q" type="range" min="10" max="100" value="90"></label><div class="row"><button class="b pri dl">Download</button></div>'+XS+'<canvas style="max-width:100%;background:#0006;border-radius:8px"></canvas><p class="note">Filters need Chrome, Edge or Firefox (not iPhone Safari).</p>';
 const cv=$('canvas',box),X=cv.getContext('2d'),get=form($('.fm',box),[['file','Choose an image','image/*'],...spec]),M=()=>({PNG:'image/png',JPG:'image/jpeg',WebP:'image/webp'})[$('.fmt',box).value],Q=()=>$('.q',box).value/100;let img,tm;
 const out=()=>{if(M()=='image/png')return cv;const t=document.createElement('canvas');t.width=cv.width;t.height=cv.height;const c=t.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,t.width,t.height);c.drawImage(cv,0,0);return t};
 const R=async()=>{const v=get();if(v[0][0]&&(!img||img._f!==v[0][0])){try{img=await rd(v[0][0]);img._f=v[0][0]}catch(e){return S(box,'Your browser may not support this image format.')}}if(!img)return;draw(cv,X,img,v.slice(1));const b=await blob(out(),M(),Q());b&&S(box,'Estimated file size: '+kb(b.size))};
 box.oninput=box.onchange=()=>{clearTimeout(tm);tm=setTimeout(R,120)};
 $('.dl',box).onclick=async()=>{if(!img)return S(box,NF);dl(await blob(out(),M(),Q()),'navaar-'+name+'.'+$('.fmt',box).value.toLowerCase());S(box,'Downloaded')};return R}
const P={'Original size':0,'Custom (use width and height below)':1,'Instagram Post 1080×1080':[1080,1080],'Instagram Portrait 1080×1350':[1080,1350],'Instagram Story / Reel 1080×1920':[1080,1920],'TikTok 1080×1920':[1080,1920],'Facebook Post 1200×630':[1200,630],'YouTube Thumbnail 1280×720':[1280,720],'WhatsApp Profile 500×500':[500,500],'LinkedIn Post 1200×627':[1200,627]};
const fit=(t,W,x,fs)=>{while(x.measureText(t).width>W*.94&&fs>10){fs-=2;x.font=x.font.replace(/\d+px/,fs+'px')}};
/* ---- lists & shells ---- */
function flist(box,accept,label){const a=[];box.innerHTML=`<label>${label}<input type="file" accept="${accept}" multiple></label><div class="fl"></div>`;const L=$('.fl',box),d=()=>{L.innerHTML=a.map((f,i)=>`<div class="row" style="align-items:center;margin:4px 0"><span style="flex:1;word-break:break-all;font-size:13px">${i+1}. ${esc(f.name)}</span><button class="b" data-m="${i}:-1" aria-label="Move up">↑</button><button class="b" data-m="${i}:1" aria-label="Move down">↓</button><button class="b" data-m="${i}:0" aria-label="Remove">✕</button></div>`).join('')};
 $('input',box).onchange=e=>{a.push(...e.target.files);e.target.value='';d()};L.onclick=e=>{const b=e.target.closest('button');if(!b)return;const[i,s]=b.dataset.m.split(':').map(Number);if(!s)a.splice(i,1);else if(a[i+s])[a[i],a[i+s]]=[a[i+s],a[i]];d()};return a}
function shell(box,spec,label,fn){box.innerHTML='<div class="fm"></div><div class="row"><button class="b pri go">'+label+'</button></div>'+XS+'<div class="res"></div>';const g=form($('.fm',box),spec);$('.go',box).onclick=async()=>{S(box,'Processing…');try{await fn(g(),box)}catch(e){S(box,e&&e.user?e.message:E)}}}
function rng(s,n){const o=[];if(!s.trim())return[...Array(n).keys()];for(const p of s.split(',')){const m=p.trim().match(/^(\d+)(?:\s*-\s*(\d+))?$/);if(!m)throw U('Use page numbers like 1-3,5');const a=+m[1],b=+(m[2]||m[1]);if(a<1||b>n||a>b)throw U('Pages must be between 1 and '+n);for(let i=a;i<=b;i++)o.push(i-1)}return o}
const pdfOut=async(d,box,m)=>{dl(new Blob([await d.save()],{type:'application/pdf'}),'navaar-pdf.pdf');S(box,m||'Done. Your PDF was downloaded.')},ld=async f=>{await lib(PL);return PDFLib.PDFDocument.load(await f.arrayBuffer(),{ignoreEncryption:true})},lib=u=>loadJS(u),pj=async f=>{await lib(PJ);pdfjsLib.GlobalWorkerOptions.workerSrc=PJ.replace('pdf.min','pdf.worker.min');return pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise};
/* ---- registry ---- */
window.NVX={
imgedit:b=>imgTool(b,'image',[['r','Crop left %',0,45,0],['r','Crop right %',0,45,0],['r','Crop top %',0,45,0],['r','Crop bottom %',0,45,0],['sel','Rotate °',['0','90','180','270']],['sel','Flip',['None','Horizontal','Vertical']],['r','Brightness',0,200,100],['r','Contrast',0,200,100],['r','Saturation',0,300,100],['r','Blur',0,20,0],['r','Grayscale',0,100,0],['r','Border width',0,80,0],['c','Border color','#ffffff'],['s','Text on image',''],['r','Text size',10,300,60],['c','Text color','#ffffff'],['r','Text height %',0,100,85]],(cv,x,img,v)=>{const[cl,cr,ct,cb,rot,fl,br,co,sa,bl,gr,bw,bc,tx,ts,tc,ty]=v,W=img.width,H=img.height,sw=W*(1-(+cl+ +cr)/100),sh=H*(1-(+ct+ +cb)/100),r=+rot%180,B=+bw;cv.width=Math.round((r?sh:sw)+2*B);cv.height=Math.round((r?sw:sh)+2*B);x.fillStyle=bc;x.fillRect(0,0,cv.width,cv.height);x.save();x.translate(cv.width/2,cv.height/2);x.rotate(rot*Math.PI/180);x.scale(fl=='Horizontal'?-1:1,fl=='Vertical'?-1:1);x.filter=`brightness(${br}%) contrast(${co}%) saturate(${sa}%) blur(${bl}px) grayscale(${gr}%)`;x.drawImage(img,W*cl/100,H*ct/100,sw,sh,-sw/2,-sh/2,sw,sh);x.restore();
 if(tx){x.filter='none';x.font=`700 ${ts}px "Noto Nastaliq Urdu",sans-serif`;x.fillStyle=tc;x.textAlign='center';x.textBaseline='middle';x.shadowColor='#0008';x.shadowBlur=8;x.fillText(tx,cv.width/2,cv.height*ty/100);x.shadowBlur=0}}),
imgsize:b=>imgTool(b,'resized',[['sel','Size preset',Object.keys(P)],['n','Custom width',1080],['n','Custom height',1080],['sel','Fit mode (Fill crops edges, Fit adds background)',['Fill','Fit','Stretch']],['c','Background for Fit','#000000']],(cv,x,img,v)=>{const[p,cw,ch,ft,bg]=v;let[w,h]=P[p]===0?[img.width,img.height]:P[p]===1?[+cw,+ch]:P[p];w=Math.min(8000,Math.max(1,Math.round(w||1)));h=Math.min(8000,Math.max(1,Math.round(h||1)));cv.width=w;cv.height=h;x.fillStyle=bg;x.fillRect(0,0,w,h);if(ft=='Stretch')return x.drawImage(img,0,0,w,h);const k=(ft=='Fill'?Math.max:Math.min)(w/img.width,h/img.height),dw=img.width*k,dh=img.height*k;x.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh)}),
imgwm:b=>{let logo,lf,R;R=imgTool(b,'watermarked',[['s','Watermark text','© Navaar'],['r','Text size %',2,30,8],['r','Opacity %',5,100,50],['sel','Position',['Center','Bottom right','Top left','Tiled']],['c','Text color','#ffffff'],['file','Logo image (optional)','image/*'],['r','Logo size %',5,60,20]],(cv,x,img,v)=>{const[tx,ts,op,pos,tc,lg,lz]=v,W=img.width,H=img.height,fs=W*ts/100,pad=W*.03;cv.width=W;cv.height=H;x.drawImage(img,0,0);const f=lg[0];if(f!==lf){lf=f;logo=null;if(f)rd(f).then(i=>{logo=i;R()}).catch(()=>{})}
 x.globalAlpha=op/100;const place=(w,h,fn)=>{if(pos=='Tiled'){x.save();x.rotate(-.4);for(let yy=-H;yy<H*2;yy+=h*3)for(let xx=-W;xx<W*2;xx+=w*1.8)fn(xx,yy);x.restore()}else fn(pos=='Center'?(W-w)/2:pos=='Top left'?pad:W-w-pad,pos=='Center'?(H-h)/2:pos=='Top left'?pad:H-h-pad)};
 if(tx){x.font=`700 ${fs}px "Noto Nastaliq Urdu",sans-serif`;x.fillStyle=tc;x.textBaseline='top';x.textAlign='left';place(x.measureText(tx).width,fs,(a,c)=>x.fillText(tx,a,c))}if(logo){const lw=W*lz/100,lh=lw*logo.height/logo.width;place(lw,lh,(a,c)=>x.drawImage(logo,a,c,lw,lh))}x.globalAlpha=1});return R},
imgblur:b=>imgTool(b,'blurred',[['r','Area left %',0,100,30],['r','Area top %',0,100,30],['r','Area width %',1,100,30],['r','Area height %',1,100,20],['sel','Style',['Blur','Pixelate']],['r','Strength',2,60,20]],(cv,x,img,v)=>{const[l,t,w,h,st,s]=v,W=img.width,H=img.height;cv.width=W;cv.height=H;x.drawImage(img,0,0);x.save();x.beginPath();x.rect(W*l/100,H*t/100,W*w/100,H*h/100);x.clip();if(st=='Blur'){x.filter=`blur(${s}px)`;x.drawImage(img,0,0)}else{const k=Math.max(2,+s),c=document.createElement('canvas');c.width=Math.ceil(W/k);c.height=Math.ceil(H/k);c.getContext('2d').drawImage(img,0,0,c.width,c.height);x.imageSmoothingEnabled=false;x.drawImage(c,0,0,W,H)}x.restore()}),
meme:b=>imgTool(b,'meme',[['s','Top text',''],['s','Bottom text',''],['r','Text size %',4,20,10],['c','Text color','#ffffff']],(cv,x,img,v)=>{const[tt,bt,sz,c]=v,W=img.width,H=img.height,fs=W*sz/100;cv.width=W;cv.height=H;x.drawImage(img,0,0);x.font=`${fs}px Impact,"Arial Black",sans-serif`;x.textAlign='center';x.lineJoin='round';x.lineWidth=fs/6;x.strokeStyle='#000';x.fillStyle=c;const dr=(t,y,bs)=>{t=t.toUpperCase();x.font=`${fs}px Impact,"Arial Black",sans-serif`;fit(t,W,x,fs);x.textBaseline=bs;x.strokeText(t,W/2,y);x.fillText(t,W/2,y)};tt&&dr(tt,fs*.25,'top');bt&&dr(bt,H-fs*.25,'bottom')}),
img2pdf:b=>{b.innerHTML='<div></div><div></div>';const A=flist(b.children[0],'image/*','Add images (order = page order)');shell(b.children[1],[['sel','Page size',['A4','Letter','Fit image']],['sel','Orientation',['Portrait','Landscape']]],'Create PDF',async(v,bx)=>{if(!A.length)throw U('Please add at least one image.');await lib(PL);const o=await PDFLib.PDFDocument.create();for(const f of A){const im=await rd(f),c=document.createElement('canvas');c.width=im.width;c.height=im.height;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(im,0,0);const e=await o.embedJpg(await(await blob(c,'image/jpeg',.92)).arrayBuffer()),F=v[0]=='Fit image';let[pw,ph]=F?[im.width,im.height]:v[0]=='Letter'?[612,792]:[595,842];if(!F&&v[1]=='Landscape')[pw,ph]=[ph,pw];const m=F?0:24,k=Math.min((pw-2*m)/im.width,(ph-2*m)/im.height),w=im.width*k,h=im.height*k;o.addPage([pw,ph]).drawImage(e,{x:(pw-w)/2,y:(ph-h)/2,width:w,height:h})}await pdfOut(o,bx,'Done. '+A.length+' image(s) saved as PDF.')})},
/* ---- PDF ---- */
pdfmerge:b=>{b.innerHTML='<div></div><div></div>';const A=flist(b.children[0],'application/pdf','Add PDF files (order = merge order)');shell(b.children[1],[],'Merge PDFs',async(v,bx)=>{if(A.length<2)throw U('Please add at least two PDFs.');const o=await PDFLib0(),n=[];for(const f of A){const d=await ld(f);(await o.copyPages(d,d.getPageIndices())).forEach(p=>o.addPage(p))}await pdfOut(o,bx,'Done. '+o.getPageCount()+' pages merged.')})},
pdfpages:b=>shell(b,[['file','Choose a PDF','application/pdf'],['sel','Action',['Extract pages','Delete pages','Rotate pages']],['s','Pages, e.g. 1-3,5 (empty = all). For Extract you can reorder: 3,1,2',''],['sel','Rotation (for Rotate)',['90','180','270']]],'Run',async(v,bx)=>{const f=v[0][0];if(!f)throw U(NF);const s=await ld(f),n=s.getPageCount(),{PDFDocument,degrees}=PDFLib;let ix=rng(v[2],n);const all=[...Array(n).keys()],o=await PDFDocument.create();if(v[1]=='Delete pages'){const z=new Set(ix);ix=all.filter(i=>!z.has(i));if(!ix.length)throw U('You cannot delete every page.')}
 if(v[1]=='Rotate pages'){const z=new Set(ix);(await o.copyPages(s,all)).forEach((p,i)=>{if(z.has(i))p.setRotation(degrees((p.getRotation().angle+ +v[3])%360));o.addPage(p)})}else(await o.copyPages(s,ix)).forEach(p=>o.addPage(p));await pdfOut(o,bx,'Done. Your PDF has '+o.getPageCount()+' pages.')}),
pdfmark:b=>shell(b,[['file','Choose a PDF','application/pdf'],['s','Watermark text (English letters and numbers only)',''],['r','Watermark size',20,150,60],['r','Opacity %',5,100,25],['sel','Page numbers',['None','Bottom center','Bottom right']]],'Apply',async(v,bx)=>{const f=v[0][0];if(!f)throw U(NF);const d=await ld(f),{StandardFonts,rgb,degrees}=PDFLib,ft=await d.embedFont(StandardFonts.Helvetica),t=v[1].trim(),n=d.getPageCount();d.getPages().forEach((p,i)=>{const{width:w,height:h}=p.getSize();try{if(t){const sz=+v[2],tw=ft.widthOfTextAtSize(t,sz);p.drawText(t,{x:w/2-tw*.354,y:h/2-tw*.354,size:sz,font:ft,color:rgb(.5,.5,.5),opacity:v[3]/100,rotate:degrees(45)})}if(v[4]!='None'){const s=`${i+1} / ${n}`,tw=ft.widthOfTextAtSize(s,10);p.drawText(s,{x:v[4]=='Bottom right'?w-tw-30:(w-tw)/2,y:20,size:10,font:ft,color:rgb(.2,.2,.2)})}}catch(e){throw U('Watermark supports English letters and numbers only.')}});await pdfOut(d,bx)}),
pdf2img:b=>shell(b,[['file','Choose a PDF','application/pdf'],['sel','Quality',['1x','1.5x','2x']],['sel','Format',['JPG','PNG']]],'Convert pages',async(v,bx)=>{const f=v[0][0];if(!f)throw U(NF);const d=await pj(f),n=Math.min(d.numPages,50),jp=v[2]=='JPG',res=$('.res',bx);res.innerHTML='';for(let i=1;i<=n;i++){S(bx,`Rendering page ${i} of ${n}…`);const p=await d.getPage(i),vp=p.getViewport({scale:parseFloat(v[1])*1.5}),c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);await p.render({canvasContext:x,viewport:vp}).promise;const u=URL.createObjectURL(await blob(c,jp?'image/jpeg':'image/png',.92));res.insertAdjacentHTML('beforeend',`<div style="display:inline-block;margin:6px;text-align:center"><img src="${u}" alt="Page ${i}" style="width:150px;border-radius:6px;display:block"><a class="b" style="margin-top:6px" href="${u}" download="navaar-page-${i}.${jp?'jpg':'png'}">Download page ${i}</a></div>`)}S(bx,'Done. '+n+' page(s) ready'+(d.numPages>n?' (first 50 only).':'.'))}),
pdftext:b=>shell(b,[['file','Choose a PDF','application/pdf']],'Extract text',async(v,bx)=>{const f=v[0][0];if(!f)throw U(NF);const d=await pj(f);let t='';for(let i=1;i<=d.numPages;i++)t+=(await(await d.getPage(i)).getTextContent()).items.map(z=>z.str).join(' ')+'\n\n';if(!t.trim())throw U('No selectable text found. This may be a scanned PDF. OCR is not supported here.');const r=$('.res',bx);r.innerHTML='<textarea readonly dir="auto" style="min-height:260px"></textarea><div class="row"><button class="b cp">Copy</button><button class="b dt">Download .txt</button></div>';$('textarea',r).value=t;$('.cp',r).onclick=()=>navigator.clipboard.writeText(t).then(()=>S(bx,'Copied'),()=>S(bx,'Copy is not available in this browser.'));$('.dt',r).onclick=()=>dl(new Blob([t],{type:'text/plain'}),'navaar-pdf-text.txt');S(bx,'Done.')}),
/* ---- QR & barcode ---- */
qr:async b=>{await lib(QRL);qrcode.stringToBytes=qrcode.stringToBytesFuncs['UTF-8'];const e=encodeURIComponent,TY={URL:[['Website URL'],c=>c[0]],Text:[['Text'],c=>c[0]],Phone:[['Phone number'],c=>'tel:'+c[0]],Email:[['Email address','Subject','Message'],c=>`mailto:${c[0]}?subject=${e(c[1])}&body=${e(c[2])}`],WhatsApp:[['Number with country code, e.g. 923001234567','Message'],c=>`https://wa.me/${c[0].replace(/\D/g,'')}?text=${e(c[1])}`],'Wi-Fi':[['Network name','Password','Security: WPA, WEP or nopass'],c=>`WIFI:T:${c[2]||'WPA'};S:${c[0]};P:${c[1]};;`],vCard:[['Full name','Phone','Email','Organization'],c=>`BEGIN:VCARD\nVERSION:3.0\nFN:${c[0]}\nTEL:${c[1]}\nEMAIL:${c[2]}\nORG:${c[3]}\nEND:VCARD`]};
 b.innerHTML='<label>QR type<select class="ty">'+Object.keys(TY).map(k=>`<option>${k}</option>`).join('')+'</select></label><div class="f1"></div><div class="f2"></div><div class="row"><button class="b pri dp">Download PNG</button><button class="b ds">Download SVG</button></div>'+XS+'<canvas style="max-width:100%;background:#fff;border-radius:8px"></canvas><p class="note">SVG does not include the logo.</p>';
 const cv=$('canvas',b),x=cv.getContext('2d');let g1,logo,lf,svg='';const g2=form($('.f2',b),[['c','QR color','#000000'],['c','Background','#ffffff'],['sel','Size',['512','768','1024']],['sel','Error correction',['M','L','Q','H']],['file','Logo in the center (optional)','image/*']]);
 const fields=()=>{g1=form($('.f1',b),TY[$('.ty',b).value][0].map(l=>['s',l,'']))},R=()=>{const d=TY[$('.ty',b).value][1](g1()),[fg,bg,sz,ec,lg]=g2();if(!d.replace(/[^\S\n]*/g,'').replace(/^[a-z:]*\?*/i,'').trim()||!g1()[0].trim()){svg='';x.clearRect(0,0,cv.width,cv.height);return S(b,'Type your content to create a QR code.')}const f=lg[0];if(f!==lf){lf=f;logo=null;if(f)rd(f).then(i=>{logo=i;R()}).catch(()=>{})}
  const q=qrcode(0,f?'H':ec);q.addData(d);try{q.make()}catch(err){svg='';return S(b,'This content is too long for a QR code.')}const n=q.getModuleCount(),m=4,s=Math.max(1,Math.floor(+sz/(n+2*m))),N=s*(n+2*m);cv.width=cv.height=N;x.fillStyle=bg;x.fillRect(0,0,N,N);x.fillStyle=fg;let p='';for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(q.isDark(r,c)){x.fillRect((c+m)*s,(r+m)*s,s,s);p+=`M${c+m} ${r+m}h1v1h-1z`}
  if(logo){const L=N*.22,o=(N-L)/2;x.fillStyle=bg;x.fillRect(o-6,o-6,L+12,L+12);x.drawImage(logo,o,o,L,L)}svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${n+2*m} ${n+2*m}" shape-rendering="crispEdges"><rect width="100%" height="100%" fill="${bg}"/><path d="${p}" fill="${fg}"/></svg>`;S(b,'')};
 fields();$('.ty',b).onchange=()=>{fields();R()};b.oninput=b.onchange=e=>{if(e.target.className!='ty')R()};$('.dp',b).onclick=async()=>{if(!svg)return S(b,'Type your content first.');dl(await blob(cv,'image/png'),'navaar-qr.png')};$('.ds',b).onclick=()=>{if(!svg)return S(b,'Type your content first.');dl(new Blob([svg],{type:'image/svg+xml'}),'navaar-qr.svg')}},
qrscan:async b=>{await lib(JS);b.innerHTML='<div class="row"><button class="b pri st">Start camera</button><button class="b sp">Stop</button></div><video playsinline muted style="width:100%;max-width:420px;border-radius:10px;display:none"></video><label>Or scan from an image<input type="file" accept="image/*" class="fi"></label>'+XS+'<pre class="rs" style="display:none"></pre><div class="row lk"></div>';const v=$('video',b);let ms,on=0;const show=t=>{const r=$('.rs',b);r.style.display='block';r.textContent=t;$('.lk',b).innerHTML=`<button class="b cp">Copy</button>`+(/^https?:\/\//i.test(t)?`<a class="b" href="${esc(t)}" target="_blank" rel="noopener noreferrer">Open link</a>`:'');$('.cp',b).onclick=()=>navigator.clipboard.writeText(t).then(()=>S(b,'Copied'),()=>{});S(b,'QR code found.')},stop=()=>{on=0;ms&&ms.getTracks().forEach(t=>t.stop());ms=null;v.style.display='none'};clean=stop;
 const dec=(s,w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.drawImage(s,0,0,w,h);return jsQR(x.getImageData(0,0,w,h).data,w,h)};
 $('.st',b).onclick=async()=>{try{ms=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}})}catch(e){return S(b,'Camera permission is required to scan.')}v.srcObject=ms;v.style.display='block';await v.play();on=1;S(b,'Point the camera at a QR code…');const L=()=>{if(!on)return;if(v.videoWidth){const c=dec(v,v.videoWidth,v.videoHeight);if(c){stop();return show(c.data)}}requestAnimationFrame(L)};L()};$('.sp',b).onclick=stop;
 $('.fi',b).onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const i=await rd(f),c=dec(i,i.width,i.height);c?show(c.data):S(b,'No QR code found in this image.')}catch(x){S(b,'Your browser may not support this image format.')}}},
barcode:async b=>{await lib(JB);b.innerHTML='<div class="fm"></div><div class="row"><button class="b pri dp">Download PNG</button></div>'+XS+'<canvas style="max-width:100%;background:#fff;border-radius:8px"></canvas>';const cv=$('canvas',b),g=form($('.fm',b),[['sel','Format',['CODE128','EAN13','EAN8','UPC','CODE39','ITF14']],['s','Value','123456789012'],['r','Bar width',1,4,2],['r','Height',30,200,90],['c','Bar color','#000000'],['c','Background','#ffffff']]);let ok=0;const R=()=>{const[f,v,w,h,lc,bg]=g();if(!v.trim()){ok=0;return S(b,'Type a value to create a barcode.')}try{JsBarcode(cv,v,{format:f,width:+w,height:+h,lineColor:lc,background:bg,displayValue:true,margin:16});ok=1;S(b,'')}catch(e){ok=0;S(b,'This value is not valid for '+f+'. EAN-13 needs 12–13 digits, EAN-8 7–8, UPC 11–12, ITF-14 13–14.')}};b.oninput=b.onchange=R;R();$('.dp',b).onclick=async()=>ok?dl(await blob(cv,'image/png'),'navaar-barcode.png'):S(b,'Fix the value first.')}
};
async function PDFLib0(){await lib(PL);return PDFLib.PDFDocument.create()}
window.NVH={form,S,dl,rd,blob,XS,U,shell,flist,ld,pdfOut};};
})();
